from typing import Protocol
from uuid import UUID
from app.core.todo.entities import Todo


class AbstractTodoRepository(Protocol):
    async def add(self, todo: Todo) -> None: ...

    async def get_by_id(self, todo_id: UUID) -> Todo | None: ...

    async def list_all(self) -> list[Todo]: ...

    async def update(self, todo: Todo) -> None: ...

    async def delete(self, todo_id: UUID) -> None: ...
